### ISSUE TITLE
FancyImpute using KNN : only returns imputed rows and not whole dataframe

### ISSUE THREAD

**Issue by pablo3p** [iskandr/fancyimpute#67] opened 2018-07-20 03:53 UTC
Hi,

I looked into the code of your KNN and found a fill() method has inplace = True,
this parameter is set TRUE to ensure it returns the whole data back with missing imputed.

BUT it only returns rows that were imputed.
SO it did not do the impute processing inplace.

Hope the developer here can comment on this.
The code seems to indicate that it returns the whole data, meaning that the imputing was done inplace.

Hope you can help.

**Comment by sergeyf** [comment] 2018-07-20 14:29
Howdy. Can you please provide a self-contained code snippet so we can reproduce this on our side?

**Comment by pablo3p** [comment] 2018-07-20 16:31
Hi,
So below is the part of the code, and the line:
--> only_filled = KNN(k=3).complete(df.values)
This is your KNN method, and it only returns the imputed rows, hence it does not
impute it inplace and also not returning the whole dataset.
I have attached the CSV file as well.

I had to change the extension to .txt since the uploader here does not accept .csv.
See code below:

[Wisconsin-Cancer-Data-withHeader.csv.txt](https://github.com/iskandr/fancyimpute/files/2214673/Wisconsin-Cancer-Data-withHeader.csv.txt)


----------------------------------------------------------------------
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from fancyimpute import BiScaler, KNN, NuclearNormMinimization, SoftImpute


df = pd.read_csv('Wisconsin-Cancer-Data-withHeader.csv')

df.loc[df.BareNuc == '?', 'BareNuc'] = np.nan

only_filled = KNN(k=3).complete(df.values)
-------------------------------------------------------------------

**Comment by pablo3p** [comment] 2018-07-20 16:32
Somehow the last line of code got different font and style when I just sent it to you.

**Comment by pablo3p** [comment] 2018-07-20 16:36
Hi Sergey, thanks for reopening it.

**Comment by sergeyf** [comment] 2018-07-20 16:41
I'll take a look and get back to you.

**Comment by pablo3p** [comment] 2018-07-20 16:48
Ok, no problem.
Like I said, I got into your code, and inside in the fill() method I did see the parameter : inplace= True.

**Comment by sergeyf** [comment] 2018-07-20 22:46
Hey so I ran this code snippet on your data and I don't see the bug. The shape of the input and output is the same:

```
print(df.values.shape, only_filled.shape)
(699, 11) (699, 11)
```

**Comment by pablo3p** [comment] 2018-07-21 04:34
Hi, I assigned it to another variable and got only the imputed rows back, the return value of
only_filled. 
I will run this again and see, will get back to  you.

**Comment by pablo3p** [comment] 2018-07-23 23:17
Hi, I did get all the data returned as your code indicated, I don't know what happened when I ran it the first time though, its very odd, not sure what I did incorrectly. But at least its working the way it should.
But I have run into another issue.

**Comment by pablo3p** [comment] 2018-07-23 23:22
When i looked at the output the missing values were replaced, but replaced with real numbers, when the original data is integer based.
But what i also noticed was that when python imported the data from CSV, the numeric columns were defined , by python to not be integer but real numbers.
So does the KNN function i guess detects the types and uses that to be the output type as well.
SO if i re-cast the columns to  integer i guess that the fancyimpute KNN will also output integer values. Ok, hope you can clarify how the KNN works in terms of data-types.

**Comment by sergeyf** [comment] 2018-07-24 02:10
All of our imputers return floats: https://github.com/iskandr/fancyimpute/blob/master/fancyimpute/solver.py#L124

If you want integers, just cast the output as an `int`.

Looks like your original bug report is not an issue anymore, so I'm going to close this one!

**Closed by sergeyf** 2018-07-24 02:10 UTC
